### ISSUE TITLE
Consent form: Add anchor link to allow visitor to revisit their consent form

### ISSUE THREAD

**Issue by thao-do** [AllenInstitute/aics-fms-file-explorer-app#179]
"Cookie Settings" anchor link: add the following HTML anchor element to the bottom of the homepage to allow access to the cookie consent form <a style="cursor: pointer;" onclick="OneTrust.ToggleInfoDisplay()">Cookie Settings</a> 
Styling: centering the element - footer is not required, *note: font-family within the cookie banner and consent form is inherited from the main <html>.

**Comment by aswallace** [comment]
Closing in favor of #180
